import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test('pilot: disconnect, reload, cash sale, lost sync response, replay, refund and closing', async ({ page, context }) => {
  const failures: string[] = []; page.on('pageerror', (error) => failures.push(error.message));
  await page.goto('/');
  const origin = new URL(page.url()).origin;
  const registered = await context.request.post('/api/v1/auth/register', { headers: { Origin: origin }, data: { email: 'pilot-' + randomUUID() + '@example.com', password: randomUUID() + '-Pilot', display_name: 'DEMO automated pilot' } });
  expect(registered.status()).toBe(201);
  const session = await registered.json() as { csrf_token: string };
  const api = async (path: string, body?: unknown, key = randomUUID()) => {
    const result = body === undefined ? await context.request.get('/api/v1' + path) : await context.request.post('/api/v1' + path, { headers: { Origin: origin, 'X-CSRF-Token': session.csrf_token, 'Idempotency-Key': key }, data: body });
    expect(result.ok(), 'API ' + path + ': ' + await result.text()).toBeTruthy(); return await result.json();
  };
  const business = await api('/businesses', { name: 'DEMO Pilot browser validation', store_name: 'DEMO pilot store', store_address: 'Synthetic automated test only' }) as { id: string };
  const base = '/businesses/' + business.id;
  const stores = await api(base + '/stores') as { id: string }[];
  const path = base + '/stores/' + stores[0].id;
  const terminal = await api(path + '/terminals', { name: 'DEMO pilot counter' }) as { id: string };
  const product = await api(base + '/products', { sku: 'DEMO-PILOT-BISCUIT', name: 'DEMO pilot biscuit', unit: 'pcs', purchase_price: '18.50', landed_cost: '19', selling_price: '25', mrp: '30', gst_rate: '5', hsn: '1905', reorder_level: '5', reorder_quantity: '20', barcodes: [], confirm_distinct_product: true }) as { id: string };
  await api(path + '/opening-stock', { product_id: product.id, quantity: '10', unit_cost: '18.50', reason: 'Synthetic pilot opening count', confirmed: true });
  const account = await api(path + '/accounts', { name: 'DEMO pilot drawer', kind: 'cash', terminal_id: terminal.id, opening_amount: '1000', reason: 'Synthetic pilot funds', confirmed: true }) as { id: string };
  const shift = await api(path + '/cash-sessions', { account_id: account.id, opening_cash: '1000', reason: 'Synthetic pilot opening', confirmed: true }) as { id: string };
  await page.reload();
  await page.getByRole('button', { name: 'Offline preparation', exact: true }).click();
  await page.getByLabel('Reserve DEMO pilot biscuit').fill('8');
  await page.getByLabel('Preparation reason').fill('Synthetic pilot outage reservation');
  await page.getByLabel('Device passphrase', { exact: true }).fill('Synthetic-pilot-device-passphrase');
  await page.getByLabel('I approve this stock reservation for my till.').check();
  await page.getByRole('button', { name: 'Prepare offline till', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Till prepared and encrypted' })).toBeVisible();
  await page.getByRole('link', { name: 'Open offline till', exact: true }).click();
  await context.setOffline(true);
  await page.reload();
  await page.getByLabel('Device passphrase', { exact: true }).fill('Synthetic-pilot-device-passphrase');
  await page.getByRole('button', { name: 'Unlock till', exact: true }).click();
  await page.getByRole('button', { name: 'DEMO pilot biscuit · ₹25.00', exact: true }).click();
  await page.getByLabel('Sale quantity').fill('2');
  await page.getByLabel('Cash received').fill('100');
  await page.getByLabel('I received the cash and will give the correct change.').check();
  await page.getByRole('button', { name: 'Save cash receipt', exact: true }).click();
  await expect(page.getByText('1 pending synchronization')).toBeVisible();
  await expect(page.getByText('Total ₹50.00 · Received ₹100 · Change ₹50.00')).toBeVisible();
  await page.reload();
  await page.getByLabel('Device passphrase', { exact: true }).fill('Synthetic-pilot-device-passphrase');
  await page.getByRole('button', { name: 'Unlock till', exact: true }).click();
  await expect(page.getByText('1 pending synchronization')).toBeVisible();
  await context.setOffline(false);
  let dropped = false;
  await page.route('**/offline-leases/*/sales', async (route) => {
    if (!dropped) { const response = await route.fetch(); expect(response.status()).toBe(201); dropped = true; await route.abort('failed'); }
    else await route.continue();
  });
  await page.getByRole('button', { name: 'Synchronize receipts', exact: true }).click();
  await expect(page.getByText('1 pending synchronization')).toBeVisible();
  await expect(page.getByRole('alert').filter({ hasText: 'Requires review:' })).toBeVisible();
  await page.getByRole('button', { name: 'Synchronize receipts', exact: true }).click();
  await expect(page.getByText('0 pending synchronization')).toBeVisible();
  const sales = await api(path + '/sales') as { id: string }[]; expect(sales).toHaveLength(1);
  const stock = await api(path + '/stock') as { quantity: string }[]; expect(stock[0].quantity).toBe('8.000');
  const sessions = await api(path + '/cash-sessions') as { expected_cash: string }[]; expect(sessions[0].expected_cash).toBe('1050.00');
  let sealDropped = false;
  await page.route('**/offline-leases/*/finalize', async (route) => { if (!sealDropped) { const response = await route.fetch(); expect(response.status()).toBe(200); sealDropped = true; await route.abort('failed'); } else await route.continue(); });
  await page.getByLabel('Finalization reason').fill('Synthetic pilot all receipts synchronized');
  await page.getByLabel('All completed receipts are saved and synchronized from this till.').check();
  await page.getByRole('button', { name: 'Finalize offline session', exact: true }).click();
  await expect(page.getByText(/Finalization awaiting confirmation/)).toBeVisible();
  await expect(page.getByRole('alert').filter({ hasText: 'Could not reach' })).toBeVisible();
  await page.reload();
  await page.getByLabel('Device passphrase', { exact: true }).fill('Synthetic-pilot-device-passphrase');
  await page.getByRole('button', { name: 'Unlock till', exact: true }).click();
  await expect(page.getByText(/Finalization awaiting confirmation/)).toBeVisible();
  await page.getByLabel('All completed receipts are saved and synchronized from this till.').check();
  await page.getByRole('button', { name: 'Finalize offline session', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Unused reservation released' })).toBeVisible();
  await page.goto('/');
  await page.getByRole('button', { name: 'Corrections & returns', exact: true }).click();
  await page.getByLabel('Original receipt').selectOption(sales[0].id);
  await page.getByLabel('Return DEMO pilot biscuit').fill('1');
  const returnForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Calculate refund for review' }) });
  await returnForm.getByLabel('Reason', { exact: true }).fill('Synthetic pilot one returned packet');
  await page.getByLabel('I have checked the goods and original receipt.').check();
  await page.getByRole('button', { name: 'Calculate refund for review', exact: true }).click();
  await expect(page.getByText('Exact refund ₹25.00')).toBeVisible();
  await page.getByLabel('I approve paying this refund.').check();
  await page.getByRole('button', { name: 'Approve and record refund', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Correction recorded:' })).toBeVisible();
  const finalStock = await api(path + '/stock') as { quantity: string }[]; expect(finalStock[0].quantity).toBe('9.000');
  const closing = await api(path + '/cash-sessions/' + shift.id + '/close', { expected_cash: '1025', actual_cash: '1025', reason: 'Synthetic balanced pilot cash closing', confirmed: true }) as { variance: string };
  expect(closing.variance).toBe('0.00'); expect(failures).toEqual([]);
  const benchmarkProduct = await api(base + '/products', { sku: 'DEMO-PILOT-TIMING', name: 'DEMO pilot timing product', unit: 'pcs', purchase_price: '18.50', landed_cost: '19', selling_price: '25', mrp: '30', gst_rate: '5', hsn: '1905', reorder_level: '5', reorder_quantity: '20', barcodes: [], confirm_distinct_product: true }) as { id: string };
  await api(path + '/opening-stock', { product_id: benchmarkProduct.id, quantity: '100', unit_cost: '18.50', reason: 'Synthetic performance stock', confirmed: true });
  const timedShift = await api(path + '/cash-sessions', { account_id: account.id, opening_cash: '1025', reason: 'Synthetic performance session', confirmed: true }) as { id: string };
  const samples: number[] = [];
  for (let index = 0; index < 20; index++) {
    const started = performance.now();
    await api(path + '/sales', { terminal_id: terminal.id, lines: [{ product_id: benchmarkProduct.id, quantity: '1', expected_price: '25', discount: '0' }], bill_discount: '0', payments: [{ account_id: account.id, cash_session_id: timedShift.id, method: 'cash', amount: '25' }], confirmed: true });
    samples.push(performance.now() - started);
  }
  samples.sort((a, b) => a - b); const p95 = samples[18];
  console.log(JSON.stringify({ synthetic_online_checkout_samples: samples.length, median_ms: Math.round(samples[10]), p95_ms: Math.round(p95), context: 'single-user local/container API; no production load claim' }));
  expect(p95).toBeLessThan(2000);
  const timedClosing = await api(path + '/cash-sessions/' + timedShift.id + '/close', { expected_cash: '1525', actual_cash: '1525', reason: 'Synthetic performance cash reconciled', confirmed: true }) as { variance: string }; expect(timedClosing.variance).toBe('0.00');
  const timedStock = await api(path + '/stock') as { product_id: string; quantity: string }[]; expect(timedStock.find((item) => item.product_id === benchmarkProduct.id)?.quantity).toBe('80.000');
});
